### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by alexrest** [cristicretu/swiftui-splitview-example#1]
This project looks so cool! Thanks for sharing!

Sorry, n00b here... When I open the project in Xcode, the Preview does not load (it says "Loading iOS 17.0..."

I'm also unable to build the project to a simulator ("A build only device cannot be used to run this target. Please select an available device or choose a simulated device as the destination."

I've built and run other projects on the same machine, so I'm not sure what I'm doing wrong. Any tips?

**Comment by cristicretu** [comment]
<img width="755" alt="image" src="https://github.com/cristicretu/swiftui-splitview-example/assets/45521157/fe467d01-289c-4793-a9db-bc6406663f6a">

You have to select a target device for the simulator to run

**Comment by alexrest** [comment]
Thanks for the reply! I have it set to "Any iOS Simulator Device" which I've used for other iOS 17 projects.

<img width="495" alt="Screenshot 2024-01-23 at 1 41 34 PM" src="https://github.com/cristicretu/swiftui-splitview-example/assets/8932059/84de3945-5e76-4832-b8ae-5866c5e00ecf">

Could it be because I'm on an Intel Mac?

**Comment by cristicretu** [comment]
Think you need to download [additional simulators](https://developer.apple.com/documentation/safari-developer-tools/adding-additional-simulators)

**Comment by alexrest** [comment]
Oh! I changed the Minimum Deployment from 17.2 to 17.0 and now it builds :) thanks for your help!
